export const STEPS = {
  HOME: "HOME",
  PASSWORD: "PASSWORD",
  SECRET_RECOVERY_PHRASE: "SECRET_RECOVERY_PHRASE",
  COMPLETED: "COMPLETED"
};

export const BLOCKCHAIN_TO_PATH = {
  SOLANA: "501",
  ETHEREUM: "60",
}
